# Generated by Django 3.0.7 on 2020-06-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200623_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
