# Generated by Django 3.0.7 on 2020-06-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200623_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Team'),
        ),
    ]
