# Generated by Django 3.0.7 on 2020-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20200623_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
