# Generated by Django 3.0.7 on 2020-06-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.AddField(
            model_name='player',
            name='round_drafted',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='selection_number',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team_drafted',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='year_drafted',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
