# Generated by Django 3.0.7 on 2020-06-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20200625_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draft',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='draft_team', to='stats.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team', to='stats.Team'),
        ),
    ]
