# Generated by Django 3.0.7 on 2020-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20200626_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_active',
            field=models.BooleanField(default=False),
        ),
    ]
