# Generated by Django 3.0.7 on 2020-06-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_team_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draft',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='draft', to='stats.Team'),
        ),
    ]
