# Generated by Django 3.0.7 on 2020-06-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20200626_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draft',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='stats.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='stats.Team'),
        ),
    ]
