# Generated by Django 3.0.7 on 2020-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20200626_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
