# Generated by Django 3.0.7 on 2020-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_age',
            field=models.IntegerField(default=0),
        ),
    ]
