# Generated by Django 3.0.7 on 2020-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20200707_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
