# Generated by Django 3.0.7 on 2020-07-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_auto_20200724_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
