# Generated by Django 3.0.7 on 2020-07-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20200724_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_city',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_country',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoot_catches',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(default='N/A', max_length=5),
        ),
    ]
