# Generated by Django 3.0.7 on 2020-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='update_edited',
        ),
        migrations.AddField(
            model_name='update',
            name='update_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='edited'),
        ),
    ]
