# Generated by Django 3.0.7 on 2020-07-19 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='update_content',
        ),
        migrations.RemoveField(
            model_name='update',
            name='update_published',
        ),
        migrations.RemoveField(
            model_name='update',
            name='update_title',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('post_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
